/* eslint-disable */
// This file is generated by contract facts. Do not edit by hand.

export const outputSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Demo.ResourceWorkflow.Contract.PrepareWorkflow.Output",
  "title": "PrepareWorkflowOutput",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "ready": {
      "type": "boolean"
    },
    "summary": {
      "type": "string"
    },
    "reviewHint": {
      "type": "string"
    }
  },
  "required": [
    "ready",
    "summary",
    "reviewHint"
  ]
} as const
