/* eslint-disable */
// This file is generated by contract facts. Do not edit by hand.

export const inputSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Demo.ResourceWorkflow.Contract.PrepareProcedure.Input",
  "title": "PrepareProcedureInput",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "procedureName": {
      "type": "string"
    },
    "objective": {
      "type": "string"
    },
    "audience": {
      "type": "string"
    }
  },
  "required": [
    "procedureName",
    "objective"
  ]
} as const
