/* eslint-disable */
// This file is generated by contract facts. Do not edit by hand.

export const outputSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Demo.ResourceWorkflow.Contract.PrepareProcedure.Output",
  "title": "PrepareProcedureOutput",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "accepted": {
      "type": "boolean"
    },
    "summary": {
      "type": "string"
    },
    "nextStep": {
      "type": "string"
    }
  },
  "required": [
    "accepted",
    "summary",
    "nextStep"
  ]
} as const
