/* eslint-disable */
// This file is generated by contract facts. Do not edit by hand.

export const inputSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Demo.ResourceWorkflow.Contract.ReservationApproveAction.Input",
  "title": "ReservationApproveActionInput",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "approvedBy": {
      "type": "string"
    },
    "evidenceRef": {
      "type": "string"
    }
  },
  "required": [
    "approvedBy"
  ]
} as const
