/* eslint-disable */
// This file is generated by contract facts. Do not edit by hand.

export const outputSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Demo.ResourceWorkflow.Contract.ReservationApproveAction.Output",
  "title": "ReservationApproveActionOutput",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "done": {
      "type": "boolean"
    },
    "summary": {
      "type": "string"
    },
    "workflowState": {
      "type": "string",
      "enum": [
        "Requested",
        "Approved"
      ]
    }
  },
  "required": [
    "done",
    "summary",
    "workflowState"
  ]
} as const
