/* eslint-disable */
// This file is generated by contract facts. Do not edit by hand.

import { inputSchema as input0, outputSchema as output0 } from "./PrepareWorkflow"

export const schemaCatalog = [input0, output0] as const
