import { mkdtemp, readFile, writeFile, mkdir } from "node:fs/promises"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { describe, expect, test } from "bun:test"
import { compileContractSchemas } from "./index"

describe("contract-schema-compiler", () => {
  test("generates schemas from TypeScript type information and shared imports", async () => {
    const root = await mkdtemp(join(tmpdir(), "contract-schema-compiler-"))
    const contractDir = join(root, "src", "Function", "PrepareThing")
    await mkdir(join(root, "src", "Shared"), { recursive: true })
    await mkdir(contractDir, { recursive: true })
    await writeFile(join(root, "src", "Shared", "index.ts"), [
      'export type Readiness = "Draft" | "Ready"',
      "export interface SharedSubject {",
      "  id: string",
      "  labels: Record<string, string>",
      "}",
      "",
    ].join("\n"))
    await writeFile(join(contractDir, "input.ts"), [
      'import type { Readiness, SharedSubject } from "../../Shared"',
      "export interface PrepareThingInput {",
      "  name: string",
      "  readiness?: Readiness",
      "  tags: string[]",
      "  subject: SharedSubject",
      "  hint: string | null",
      "  coordinates: [number, number]",
      "}",
      "",
    ].join("\n"))
    await writeFile(join(contractDir, "output.ts"), [
      "export interface PrepareThingOutput {",
      "  ok: boolean",
      "}",
      "",
    ].join("\n"))
    await writeFile(join(contractDir, "contract.json"), JSON.stringify({
      kind: "Contract",
      fqn: "Demo.ResourceWorkflow.Contract.Function.PrepareThing",
      input: { source: "input.ts", export: "PrepareThingInput", schemaId: "Demo.Input" },
      output: { source: "output.ts", export: "PrepareThingOutput", schemaId: "Demo.Output" },
    }, null, 2))

    const report = await compileContractSchemas({ packageRoot: root })
    expect(report.facts).toHaveLength(1)
    const generated = await readFile(join(contractDir, "input.schema.generated.ts"), "utf8")
    expect(generated).toContain('"enum": [')
    expect(generated).toContain('"Draft"')
    expect(generated).toContain('"tags"')
    expect(generated).toContain('"hint"')
    expect(generated).toContain('"type": "null"')
    expect(generated).toContain('"prefixItems"')
    expect(generated).toContain('"additionalProperties": {')
    expect(await readFile(join(contractDir, "index.ts"), "utf8")).toContain("export type { PrepareThingInput }")
    expect(await readFile(join(root, "src", "Function", "schema-catalog.generated.ts"), "utf8")).toContain("schemaCatalog")

    await compileContractSchemas({ packageRoot: root, checkOnly: true })
  })

  test("removes stale generated projections that no longer have a contract fact", async () => {
    const root = await mkdtemp(join(tmpdir(), "contract-schema-compiler-stale-"))
    const activeDir = join(root, "src", "Function", "Active")
    const staleDir = join(root, "src", "Function", "Stale")
    await mkdir(activeDir, { recursive: true })
    await mkdir(staleDir, { recursive: true })
    await writeFile(join(activeDir, "input.ts"), "export interface ActiveInput { value: string }\n")
    await writeFile(join(activeDir, "output.ts"), "export interface ActiveOutput { ok: boolean }\n")
    await writeFile(join(activeDir, "contract.json"), JSON.stringify({
      kind: "Contract",
      fqn: "Demo.ResourceWorkflow.Contract.Function.Active",
      input: { source: "input.ts", export: "ActiveInput", schemaId: "Demo.Active.Input" },
      output: { source: "output.ts", export: "ActiveOutput", schemaId: "Demo.Active.Output" },
    }))
    await writeFile(join(staleDir, "input.schema.generated.ts"), "stale\n")
    await writeFile(join(staleDir, "index.ts"), "// This file is generated by contract facts. Do not edit by hand.\n")

    await compileContractSchemas({ packageRoot: root })

    await expect(readFile(join(staleDir, "input.schema.generated.ts"), "utf8")).rejects.toThrow()
    await expect(readFile(join(staleDir, "index.ts"), "utf8")).rejects.toThrow()
  })
})
